# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installing Repo (a Google-built repository-management tool that runs on top of Git)
      - name: Installing Repo
        run: |
          export REPO=$(mktemp /tmp/repo.XXXXXXXXX)
          curl -o ${REPO} https://storage.googleapis.com/git-repo-downloads/repo
          gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
          mkdir -p ~/bin
          curl -s https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ${REPO} && install -m 755 ${REPO} ~/bin/repo
          repo version

      # Initializing a Repo client
      - name: Initializing a Repo client
        run: |
          mkdir aosp
          cd aosp
          git config --global user.name nguoianphu
          git config --global user.email nguoianphu@gmail.com
          repo init -u https://android.googlesource.com/platform/manifest -b master --partial-clone --clone-filter=blob:limit=10M
          repo sync -c -j8
          
          
